<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Province</name>
   <tag></tag>
   <elementGuidId>bc1f429c-1942-42fb-8e19-95eb9b927538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.select2-selection__placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-billing_state-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be409388-9cd7-45ba-8d05-596985286167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>6bb39163-07c3-4d7e-ac3f-0e8970551f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an option…</value>
      <webElementGuid>c0453efd-0702-46ff-a5f5-48ed66b82852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_state-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>835ea83c-ae6d-48a3-9f95-7e8a48ca01dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>13835508-50a6-4310-bd61-7c7726054942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>2853c033-cba0-4618-b51f-3b6e66f9ba07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an option…</value>
      <webElementGuid>63b597ef-2239-4b38-917b-22244e3019c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_state-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>ef9cbcf8-a28a-4673-839e-9cb4ee592ed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-billing_state-container']/span</value>
      <webElementGuid>bd4e79c0-cb83-4b04-9cc9-46bba49da45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::span[6]</value>
      <webElementGuid>593364ce-4f2e-471e-9d3b-e79cca840bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::span[3]</value>
      <webElementGuid>ef02c2f8-7d08-4c6a-be01-99c137bc5ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[@id='select2-billing_state-container']</value>
      <webElementGuid>1ffd7acf-7c76-4acd-8571-48a49b56e509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select an option…' or . = 'Select an option…')]</value>
      <webElementGuid>f42fe641-775e-4f72-8a94-a617fe972201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
