<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Color Selected</name>
   <tag></tag>
   <elementGuidId>5091dcd9-cd06-46e5-9b21-a6545f5b5754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='color']/option[@selected]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>05a9c81d-e8ef-4c8c-a8ce-913044868759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>color</value>
      <webElementGuid>f60d59c2-9c79-40d4-ad9b-37a79513f084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_color</value>
      <webElementGuid>165c8f22-0786-453a-a4d2-999efb749982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_color</value>
      <webElementGuid>8ba16b4e-5320-4944-9b5d-c0c71d21514e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>b572fbcd-7172-4cb7-8039-777e83788023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionRedWhiteBlack</value>
      <webElementGuid>79fd9eb5-0556-4234-896c-ceb7e75b18c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;color&quot;)</value>
      <webElementGuid>cc1e569b-a629-4365-9ff1-f1d954ab35ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Modal Compare/iframe Compare Products</value>
      <webElementGuid>71101b16-985e-4cd4-a643-402fd3876d68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='color']</value>
      <webElementGuid>15aba33e-b70c-4c26-9d03-0c46504dee60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-704']/div/div[2]/form/table/tbody/tr/td/select</value>
      <webElementGuid>3331e0ae-d64c-4472-8fc5-3372892c9076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[1]</value>
      <webElementGuid>8e1f0e12-93a2-4ad0-b49b-6fc5a7a3cada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size &amp; Fit'])[1]/following::select[1]</value>
      <webElementGuid>cd39439e-211c-46a3-b905-a23734dc0644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/preceding::select[1]</value>
      <webElementGuid>c0d1e932-7ff0-4b5c-b3ea-7589971b6afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY'])[1]/preceding::select[2]</value>
      <webElementGuid>2fbbb699-b1b7-45bf-9b0e-1f851a89dda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[@id='color']/option[@selected]</value>
      <webElementGuid>2eb24bf6-3652-4fe9-b897-480287e13d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'color' and @name = 'attribute_color' and (text() = 'Choose an optionRedWhiteBlack' or . = 'Choose an optionRedWhiteBlack')]</value>
      <webElementGuid>609d4b0d-4725-4a10-a3fb-71025db18187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
