<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe Compare Products</name>
   <tag></tag>
   <elementGuidId>7b3f2aef-01a0-4282-8cee-a79ba18f25e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;1670847168856&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cboxLoadedContent']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f63d6e59-ce2c-4ca0-a80d-772196484341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c6dbe58a-a467-4cfd-9770-7c819195bad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1670847168856</value>
      <webElementGuid>9bdf1b76-dbdc-46a6-bf49-f78c1b85c034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/?action=yith-woocompare-view-table&amp;iframe=yes</value>
      <webElementGuid>bce23f34-5853-4ecb-8cf7-2f0ae51b961d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cboxIframe</value>
      <webElementGuid>c394d2f6-0012-4015-89bf-76df68c968b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboxLoadedContent&quot;)/iframe[@class=&quot;cboxIframe&quot;]</value>
      <webElementGuid>81ce721f-5389-4b18-b0b6-d53189a2bfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>50b32992-eb8c-4303-a1ad-64b08738fce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0a33d507-75b4-42ad-881d-90007c89c2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1670847168856</value>
      <webElementGuid>c3457a35-49ff-4c1f-a6ad-3986aa87b164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/?action=yith-woocompare-view-table&amp;iframe=yes</value>
      <webElementGuid>3442a7e6-a8e2-487d-a01f-e6e14ee5cdb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cboxIframe</value>
      <webElementGuid>912d3ed3-5a2c-4972-8ddf-c3ee7730837e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboxLoadedContent&quot;)/iframe[@class=&quot;cboxIframe&quot;]</value>
      <webElementGuid>aeb29ee4-2cac-4c83-801b-e1add21fc6ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='1670847168856']</value>
      <webElementGuid>10c808ce-bee2-4518-bb1a-54c43fc6f912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cboxLoadedContent']/iframe</value>
      <webElementGuid>fd4db5c1-79ed-4d62-a6d5-839b1511a4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b4a10b88-b46b-476c-ac13-38b5c64e785c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '1670847168856' and @src = '/?action=yith-woocompare-view-table&amp;iframe=yes']</value>
      <webElementGuid>4e7b0c21-3495-404f-988c-3b3c9b0ab879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[@id='cboxLoadedContent']/iframe</value>
      <webElementGuid>d09bb265-77f9-46a4-b14e-8753df2a9e72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
