<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Option</name>
   <tag></tag>
   <elementGuidId>3924690b-0630-4020-96ee-cbe21dbca813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;DataTables_Table_1&quot;)/tbody[1]/tr[@class=&quot;add-to-cart odd&quot;]/td[${number}]/a[count(. | //*[@ref_element = 'Object Repository/Modal Compare/iframe Compare Products']) = count(//*[@ref_element = 'Object Repository/Modal Compare/iframe Compare Products'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.wp-element-button.product_type_variable.add_to_cart_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_1']/tbody/tr[5]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1854fa70-df44-4a94-b51e-d19cdd9a82e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/product/pink-drop-shoulder-oversized-t-shirt/</value>
      <webElementGuid>0154ed0e-7ed3-41d9-9c41-289627c6e61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9913637c-996b-4663-820e-2f9b73c31fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button wp-element-button product_type_variable add_to_cart_button</value>
      <webElementGuid>6979c023-b05b-48a1-b3c0-e00d880956db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>1497</value>
      <webElementGuid>30d70bff-4900-4acb-89a0-43748d65d9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select options for “pink drop shoulder oversized t shirt”</value>
      <webElementGuid>25a818aa-8c14-4949-9e05-6abe73925e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>93f7c9c7-a09f-42ce-837e-4fc73adbb87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select options</value>
      <webElementGuid>5cdf9749-a9f3-4ca3-97fc-29b9c23fb930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_1&quot;)/tbody[1]/tr[@class=&quot;add-to-cart odd&quot;]/td[${number}]/a</value>
      <webElementGuid>f5a9d1ad-becc-4e14-8027-a34dbcf3ea26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Modal Compare/iframe Compare Products</value>
      <webElementGuid>b6a11c32-6f7d-4c28-a08d-239b07441afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_1']/tbody/tr[5]/td/a</value>
      <webElementGuid>fd446507-0587-4740-952b-c58f10e55607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select options')]</value>
      <webElementGuid>552264f5-de40-474b-9369-8dd1668a7f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/following::a[1]</value>
      <webElementGuid>0fd51d44-37cf-48a6-ba78-72a5e5a09207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[3]/following::a[1]</value>
      <webElementGuid>d8869730-68c3-4302-aa69-fbbf53edd930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select options'])[2]/preceding::a[1]</value>
      <webElementGuid>8f36c5b6-0282-450e-bf44-8edc3856beaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::a[2]</value>
      <webElementGuid>986e8d2f-5ec5-427f-a227-61d2e9159c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select options']/parent::*</value>
      <webElementGuid>510fd402-3325-4bfc-83ea-63489b323c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://shop.demoqa.com/product/pink-drop-shoulder-oversized-t-shirt/')]</value>
      <webElementGuid>68512324-87b0-47b4-8c10-5f833c67c9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/a</value>
      <webElementGuid>cfb70e17-cfcb-4b71-8f3a-a4dbd1c0cd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://shop.demoqa.com/product/pink-drop-shoulder-oversized-t-shirt/' and (text() = 'Select options' or . = 'Select options')]</value>
      <webElementGuid>bf225e0b-dcaa-441f-8532-c83fa28cab5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
